site_name: 'Qolei Wiki'
site_url: https://wiki.qolei.org
repo_name: 'qolei/qolei-wiki'
repo_url: 'https://github.com/qolei/qolei-wiki'
site_description: 'Wiki for the Quality of life economic initiative'
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  font:
      text: 'Overpass'
      code: 'Overpass Mono'
  logo: 'images/Qolei_org_2.png'
  favicon: 'images/favicon.ico'
extra_css:
  - 'stylesheets/extra_style.css'
extra_javascript:
  - 'javascript/extra_js.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/qolei'
    - type: 'medium'
      link: 'https://blog.qolei.org/'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/qolei/'
    - type: 'twitter'
      link: 'https://twitter.com/qolei'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/qolei/'
  feature:
    tabs: false
nav:
  - Home: 'index.md'
  - Documentation:
    - Economy: 'documentation/economy.md'
    - Governance: 'documentation/governance.md'
    - Code of Conduct: 'documentation/Code_of_Conduct.md'
    - Legal:
      - Software Licenses: 'documentation/legal/Licenses.md'
      - Terms of Use (websites): 'documentation/legal/Terms_of_use_websites.md'
      - Privacy policy: 'documentation/legal/Privacy_policy.md'
  - Initiatives:
    - Overview: 'initiatives/index.md'
    - QOLiHoP:
      - Overview: 'initiatives/qolihop/index.md'
  - Investment projects:
    - Overview: 'investment_projects/index.md'
  - Roles:
    - Overview: 'roles/index.md'
    - Vacant roles: 'roles/Vacant_Roles.md'
  - Press:
      - Press Kit: 'press/press-kit.md'
      - Media Mentions: 'press/media-mentions.md'